require('dotenv').config();
const sequelize = require('./config/database');
const { Notification } = require('./models');

async function test() {
  try {
    console.log('🔄 Connecting to database...');
    await sequelize.authenticate();
    console.log('✅ Connected to database.');

    // Sync models to make sure Notification table is created
    console.log('🔄 Syncing database schema...');
    await sequelize.sync();
    console.log('✅ Schema synchronized.');

    console.log('📝 Creating test admin notification...');
    const notif = await Notification.create({
      type: 'NEW_ORDER',
      title: 'New Order Received (Test)',
      message: 'This is a test notification generated by the verification script. Order #999 paid for $120.00.',
      metadata: { orderId: 999 }
    });

    console.log(`✅ Test notification created: ID #${notif.id}`);
    console.log(`📌 Title: ${notif.title}`);
    console.log(`📌 Message: ${notif.message}`);

    console.log('🏁 Verification finished. If your admin dashboard is open, you should see the bell ring!');
  } catch (error) {
    console.error('❌ Test failed with error:', error);
  } finally {
    await sequelize.close();
    process.exit(0);
  }
}

test();
